### ISSUE TITLE
if (pro<=0.2 and weight>=12 ) What to do with the program

### ISSUE THREAD

**Issue by xym88** [Rebwarkh/GOOSLE-Algorithm#2]

**Comment by Rebwarkh** [comment]
Hello dears.
We apologize for the late reply.
Here, is the mechanism of the algorithm that can benefit from this video. https://youtu.be/kW5LPwchs-o
For your information, a new version of the algorithm is available.

**Mechanism of Algorithm Working**
In this section, we explain the working mechanism of the algorithm. The GOOSE algorithm begins by initializing random artificial positions utilizing the upper and lower limits at arbitrary points in the search area. The global best solution was chosen for each iteration, and the best score and best position were then determined for each artificial position. There are two parameters whose values are randomly generated between [0,1], which are the rnd and pro parameters. We also randomly determined the weight parameter of the stone between [5,25] grams. These three parameters determine the mechanism through which the algorithm operates. Sequentially, these three parameters check the algorithm to find the new location of the protected goose using which equation. Initially, if the parameter rnd greater than or equal to 0.5, the parameter pro greater than 0.2, and the weight of the stone S_W greater than or equal to 12, then Eq. (3.9) is used to find the location of the goose, but if the value of pro less than or equal to 0.2 and the value of S_W less than 12, then Eq.(3.11) is used. Moreover, if the value of parameter rnd is smaller than 0.5 rnd<0.5 at this time, Eq.(3.13) is used to find the new value of X(i,:).
